# Mandatory settings

name: Wesley Aptekar-Cassels
paginate: 10
paginate_path: "/posts/page/:num/"
#url: # add site url http://example.com/

markdown: redcarpet
redcarpet:
  extensions: ["footnotes", "tables"]

# Optional settings

discus_identifier: # Add your Disqus identifier
ga_analytics: UA-89690189-1
rss_enabled: true # Change to false if not
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
social:
  github: WesleyAC
  email: W.Aptekar@gmail.com

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
permalink: posts/:slug
