# Mandatory settings

name: Wesley Aptekar-Cassels

markdown: redcarpet
redcarpet:
  extensions: ["footnotes", "tables"]

# Optional settings

ga_analytics: UA-89690189-1
email: me@wesleyac.com

# Important settings (change at own risk)

assets:
  compress:
    css: true
  sources:
    - _assets/fonts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - TODO.md
  - vendor/
gems:
  - jekyll-assets
permalink: posts/:slug
