name: Wesley Aptekar-Cassels

markdown: redcarpet
redcarpet:
  extensions: ["footnotes", "tables"]

assets:
  compress:
    css: true
  sources:
    - _assets/fonts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - bin/*
  - Gemfile
  - Gemfile.lock
  - README.md
  - TODO.md
  - vendor/*
gems:
  - jekyll-assets
permalink: posts/:slug
