name: Wesley Aptekar-Cassels

markdown: redcarpet
redcarpet:
  extensions: ["footnotes", "tables"]

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/

defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag

exclude:
  - bin/*
  - Gemfile
  - Gemfile.lock
  - README.md
  - TODO.md
  - vendor/*

permalink: posts/:slug
